---

- name: Uninstall davinci resolve
  become: true
  ansible.builtin.command:
    cmd: "{{ dresolve_install_location }}/installer --uninstall --noconfirm"
  register: uninstall_result
  changed_when: uninstall_result.rc == 0

- name: Remove unused dependencies
  become: true
  ansible.builtin.package:
    autoremove: true

...
