---

- name: Uninstall davinci resolve
  become: true
  ansible.builtin.command:
    cmd: "installer --uninstall --noconfirm"
    chdir: "{{ dresolve_install_location }}"
  register: uninstall_result
  changed_when: uninstall_result.rc == 0

- name: Remove resolve install dir
  become: true
  ansible.builtin.file:
    path: "{{ dresolve_install_location }}"
    state: "absent"

- name: Remove unused dependencies
  become: true
  ansible.builtin.package:
    autoremove: true

...
