---

- name: Display dir
  ansible.builtin.debug:
    var: dresolve_install_location

# TODO seems to pop up UI when a DISPLAY is set
- name: Uninstall davinci resolve
  become: true
  ansible.builtin.command:
    cmd: "./installer --uninstall --noconfirm --allowroot"
    chdir: "{{ dresolve_install_location }}"
  register: uninstall_result
  changed_when: uninstall_result.rc == 0

- name: Remove resolve install dir
  become: true
  ansible.builtin.file:
    path: "{{ dresolve_install_location }}"
    state: "absent"

...
