---

- name: Ensure temporary install dir exists on remote host
  become: true
  ansible.builtin.file:
    path: "{{ dresolve_package_dir }}"
    state: "directory"
    mode: "0755"
    owner: "root"
    group: "root"

# - name: Copy installer
#   become: true
#   ansible.builtin.copy:
#     src: "DaVinci_Resolve_Studio_20.3_Linux.run"
#     dest: "{{ dresolve_package_dir }}"
#     mode: "0755"
#     owner: "root"
#     group: "root"

- name: Get installer
  become: true
  ansible.builtin.get_url:
    url: "{{ dresolve_installer_src }}"
    dest: "{{ dresolve_package_dir }}"
    mode: "0755"
    owner: "root"
    group: "root"

...
