---

- name: Install debian specific package_facts dependency
  become: true
  when: ansible_distribution == "Debian"
  ansible.builtin.package:
    name: python-apt-common
    state: present

- name: Gather package facts
  ansible.builtin.package_facts:

- name: Get davinci resolve version
  ansible.builtin.command:
    cmd: "{{ dresolve_executable_path }} -v"
  register: present_dresolve_version
  failed_when: false
  changed_when: false

- name: Set davinci resolve version
  when: present_dresolve_version.rc == 0
  ansible.builtin.set_fact:
    dresolve_version_found: "{{ present_dresolve_version.stdout_lines[-1].split(' ')[-1] }}"

- name: Include get_installer
  when: dresolve_version not in (dresolve_version_found | default(''))
  ansible.builtin.include_tasks:
    file: get_installer.yml

- name: Install resolve dependencies
  become: true
  loop: "{{ dresolve_dependencies[ansible_distribution | lower] | flatten(1) }}"
  when: item not in ansible_facts.packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: true

- name: Include run_installer
  when: dresolve_version not in (dresolve_version_found | default(''))
  ansible.builtin.include_tasks:
    file: run_installer.yml

- name: Create symlink
  become: true
  ansible.builtin.file:
    src: "{{ dresolve_executable_path }}"
    dest: "{{ dresolve_symlink }}"
    state: link

- name: Remove installer package
  become: true
  ansible.builtin.file:
    path: "{{ dresolve_package_dir }}"
    state: absent

...
