---

- name: Gather package facts
  ansible.builtin.package_facts:

- name: Get davinci resolve version
  ansible.builtin.command:
    cmd: "{{ dresolve_executable_path }} -v"
  register: present_dresolve_version
  failed_when: false
  changed_when: false

- name: Set davinci resolve version
  when: present_dresolve_version.rc == 0
  ansible.builtin.set_fact:
    dresolve_version_found: "{{ present_dresolve_version.stdout_lines[-1].split(' ')[-1] }}"

- name: Include get_installer
  when: dresolve_version not in (dresolve_version_found | default(''))
  ansible.builtin.include_tasks:
    file: get_installer.yml

- name: Install resolve dependencies
  become: true
  loop: "{{ dresolve_dependencies[ansible_facts.distribution | lower] | flatten(1) }}"
  when: item not in ansible_facts.packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: true

- name: Include run_installer
  when: dresolve_version not in (dresolve_version_found | default(''))
  ansible.builtin.include_tasks:
    file: run_installer.yml

- name: Create symlink
  become: true
  ansible.builtin.file:
    src: "{{ dresolve_executable_path }}"
    dest: "{{ dresolve_symlink }}"
    state: link

- name: Fix library mismatch
  when: ansible_facts.distribution | lower == "fedora" or ansible_facts.os_family | lower == "debian"
  block:
    - name: Create backup dir
      become: true
      ansible.builtin.file:
        path: "{{ dresolve_install_location }}/libs-backup"
        state: directory
        mode: "0755"

    - name: Find conflicting glib libraries
      ansible.builtin.find:
        paths: "{{ dresolve_install_location }}/libs"
        patterns:
          - "libglib*"
          - "libgio*"
          - "libgmodule*"
        file_type: file
      register: resolve_libs_to_move

    - name: Move conflicting libraries to backup
      become: true
      loop: "{{ resolve_libs_to_move.files }}"
      loop_control:
        label: "{{ item.path | basename }}"
      when: resolve_libs_to_move.matched > 0
      ansible.builtin.command:
        cmd: >
          mv {{ item.path }}
          {{ dresolve_install_location }}/libs-backup/
      register: move_result
      changed_when: move_result.rc == 0

- name: Remove installer package
  become: true
  ansible.builtin.file:
    path: "{{ dresolve_package_dir }}"
    state: absent

...
